### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "asdas@fd.cl",
  "password": "12334r"
}


### Find a particular user with a given ID
GET http://localhost:3000/auth/5

### Find a particular user with a given email
GET http://localhost:3000/auth?email=asdas@fd.cl

### Delete an user with a given ID
DELETE http://localhost:3000/auth/2

### Update an user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "bbbbbb@aaaa.com"
}

